name: Pre-deploy 
on:
  push:
    branches:
      - "main"
jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Add migrations
        env: 
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: goose -dir ./migrations postgres "$DATABASE_URI" up
