name: Deploy
on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: go build
        run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: go test
        run: go test -v ./...

  migrate:
    needs:
      - "test"
      - "build"
    environment: peric-telegram-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Add migrations
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URL }}
        run: goose -dir ./migrations postgres $DATABASE_URL up

  deploy:
    needs: migrate
    environment: peric-telegram-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: peric-telegram-bot
          heroku_email: dmitrievoleg96@gmail.com
