name: Pre-deploy
on:
  push:
    branches:
      - "release/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: go build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: go test
        run: go test -v ./...

  migrate:
    needs:
      - "test"
      - "build"
    environment: peric-telegram-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Print secret value
        run: |
          echo ${{ secrets.DATABASE_URI }}
          echo ${{ secrets.DATABASE_URL }}
          echo ${{ secrets.DATABASE_URI }} | sed 's/./& /g'

      - name: Add migrations
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: goose -dir ./migrations postgres postgres://utlamwnpybagjv:f8b0947e68e64428af1a76d00bc0d60ddc7f95fcef37dbb2612796b8e9391a52@ec2-54-78-36-245.eu-west-1.compute.amazonaws.com:5432/danediesourpi1 status
